college=[
    {   
        "id":"jd",
        "name":"机电工程学院",
        "img":""
    },
    {   
        "id":"dx",
        "name":"电子信息工程学院",
        "img":""
    },
    {   
        "id":"cs",
        "name":"计算机科学学院",
        "img":""
    },
    {   
        "id":"sh",
        "name":"生命科学与化学学院",
        "img":""
    },
    {   
        "id":"gl",
        "name":"管理学院",
        "img":""
    },
    {   
        "id":"jj",
        "name":"经济学院",
        "img":""
    },
    {   
        "id":"cm",
        "name":"传媒与艺术设计学院",
        "img":""
    },
    {   
        "id":"wf",
        "name":"文法学院",
        "img":""
    },
    {   
        "id":"wy",
        "name":"外国语言文学学院",
        "img":""
    },
    {   
        "id":"jy",
        "name":"国际教育学院",
        "img":""
    }
]